server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/order/**
          filters:
            - name: JwtAuthenticationFilter

